steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=$_FTP_SECRET_ENC',
           '--plaintext-file=ftp.sh', '--location=global',
           '--keyring=myelin-keyring', '--key=myelin-key']

  - name: 'gcr.io/$PROJECT_ID/hugo'
    env: ['HUGO_ENV=production']

  - name: 'debian:10.1-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ftp.sh
        lftp -f """
        open $$ADDRESS
        user $$USERID $$PASSWORD
        lcd $LCD
        mirror --continue --reverse --delete --verbose public/* /public_html
        bye
        """

substitutions:
  _FTP_SECRET_ENC: ci/secrets/ftp.sh.enc